name: k8s manifestation 
description: Manipulate and apply k8s manifest
author: namgaytobden
branding:
  icon: terminal
  color: white

inputs:
  image:
    description: Docker Image name and tag
    required: true
    default: latest

  manifest_path:
    description: Manifest path
    required: true

runs:
  using: composite
  steps:
      shell: bash
    - name: Install yq
      run: sudo snap install yq
     
      shell: bash
    - run: action.sh

      shell: bash
      env: 
        DOCKER_IMAGE: ${{ inputs.image }}
        MANIFEST_PATH: ${{ inputs.manifest_path }}