name: k8s manifestation 
description: Manipulate and apply k8s manifest
author: namgaytobden
branding:
  icon: terminal
  color: blue

inputs:
  image:
    description: Docker Image name and tag
    required: true
    default: latest

  manifest_path:
    description: Manifest path
    required: true

  namespace: 
    description: namespace 
    required: true

runs:
  using: composite
  steps:
    - run: action.sh
      shell: bash
      env: 
        DOCKER_IMAGE: ${{ inputs.image }}
        MANIFEST_PATH: ${{ inputs.manifest_path }}
        NAMESPACE: $ {{ inputs.namespace }}